site_name: Uzi
theme:
  name: material
  custom_dir: docs/override


repo_name: pyuzi/django-uzi
repo_url: https://github.com/pyuzi/django-uzi
edit_uri: "blob/master/docs/"


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
  - search:
